# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(769, 315)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Heiti Std R"))
        font.setPointSize(10)
        Form.setFont(font)
        self.line_1 = QtGui.QFrame(Form)
        self.line_1.setGeometry(QtCore.QRect(0, 40, 751, 16))
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.one = QtGui.QPushButton(Form)
        self.one.setGeometry(QtCore.QRect(0, 70, 93, 28))
        self.one.setAutoFillBackground(False)
        self.one.setObjectName(_fromUtf8("one"))
        self.two = QtGui.QPushButton(Form)
        self.two.setGeometry(QtCore.QRect(100, 70, 93, 28))
        self.two.setObjectName(_fromUtf8("two"))
        self.three = QtGui.QPushButton(Form)
        self.three.setGeometry(QtCore.QRect(200, 70, 93, 28))
        self.three.setObjectName(_fromUtf8("three"))
        self.four = QtGui.QPushButton(Form)
        self.four.setGeometry(QtCore.QRect(0, 110, 93, 28))
        self.four.setObjectName(_fromUtf8("four"))
        self.five = QtGui.QPushButton(Form)
        self.five.setGeometry(QtCore.QRect(100, 110, 93, 28))
        self.five.setObjectName(_fromUtf8("five"))
        self.six = QtGui.QPushButton(Form)
        self.six.setGeometry(QtCore.QRect(200, 110, 93, 28))
        self.six.setObjectName(_fromUtf8("six"))
        self.seven = QtGui.QPushButton(Form)
        self.seven.setGeometry(QtCore.QRect(0, 150, 93, 28))
        self.seven.setObjectName(_fromUtf8("seven"))
        self.eight = QtGui.QPushButton(Form)
        self.eight.setGeometry(QtCore.QRect(100, 150, 93, 28))
        self.eight.setObjectName(_fromUtf8("eight"))
        self.nine = QtGui.QPushButton(Form)
        self.nine.setGeometry(QtCore.QRect(200, 150, 93, 28))
        self.nine.setObjectName(_fromUtf8("nine"))
        self.zero = QtGui.QPushButton(Form)
        self.zero.setGeometry(QtCore.QRect(300, 150, 93, 28))
        self.zero.setObjectName(_fromUtf8("zero"))
        self.toolButton = QtGui.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.AT = QtGui.QPushButton(Form)
        self.AT.setGeometry(QtCore.QRect(300, 230, 93, 28))
        self.AT.setObjectName(_fromUtf8("AT"))
        self.LN = QtGui.QPushButton(Form)
        self.LN.setGeometry(QtCore.QRect(0, 190, 93, 28))
        self.LN.setObjectName(_fromUtf8("LN"))
        self.add = QtGui.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(300, 70, 93, 28))
        self.add.setObjectName(_fromUtf8("add"))
        self.sub = QtGui.QPushButton(Form)
        self.sub.setGeometry(QtCore.QRect(400, 70, 93, 28))
        self.sub.setObjectName(_fromUtf8("sub"))
        self.Sin = QtGui.QPushButton(Form)
        self.Sin.setGeometry(QtCore.QRect(0, 230, 93, 28))
        self.Sin.setObjectName(_fromUtf8("Sin"))
        self.LOG = QtGui.QPushButton(Form)
        self.LOG.setGeometry(QtCore.QRect(100, 190, 93, 28))
        self.LOG.setObjectName(_fromUtf8("LOG"))
        self.Tan = QtGui.QPushButton(Form)
        self.Tan.setGeometry(QtCore.QRect(100, 230, 93, 28))
        self.Tan.setObjectName(_fromUtf8("Tan"))
        self.basee = QtGui.QPushButton(Form)
        self.basee.setGeometry(QtCore.QRect(200, 190, 93, 28))
        self.basee.setObjectName(_fromUtf8("basee"))
        self.equal = QtGui.QPushButton(Form)
        self.equal.setGeometry(QtCore.QRect(400, 110, 93, 28))
        self.equal.setObjectName(_fromUtf8("equal"))
        self.fact = QtGui.QPushButton(Form)
        self.fact.setGeometry(QtCore.QRect(400, 190, 93, 28))
        self.fact.setObjectName(_fromUtf8("fact"))
        self.power = QtGui.QPushButton(Form)
        self.power.setGeometry(QtCore.QRect(500, 150, 93, 28))
        self.power.setObjectName(_fromUtf8("power"))
        self.AC = QtGui.QPushButton(Form)
        self.AC.setGeometry(QtCore.QRect(100, 270, 93, 28))
        self.AC.setObjectName(_fromUtf8("AC"))
        self.mul = QtGui.QPushButton(Form)
        self.mul.setGeometry(QtCore.QRect(600, 70, 93, 28))
        self.mul.setObjectName(_fromUtf8("mul"))
        self.sqr = QtGui.QPushButton(Form)
        self.sqr.setGeometry(QtCore.QRect(400, 150, 93, 28))
        self.sqr.setObjectName(_fromUtf8("sqr"))
        self.AS = QtGui.QPushButton(Form)
        self.AS.setGeometry(QtCore.QRect(0, 270, 93, 28))
        self.AS.setObjectName(_fromUtf8("AS"))
        self.Cos = QtGui.QPushButton(Form)
        self.Cos.setGeometry(QtCore.QRect(200, 230, 93, 28))
        self.Cos.setObjectName(_fromUtf8("Cos"))
        self.div = QtGui.QPushButton(Form)
        self.div.setGeometry(QtCore.QRect(500, 70, 93, 28))
        self.div.setObjectName(_fromUtf8("div"))
        self.rem = QtGui.QPushButton(Form)
        self.rem.setGeometry(QtCore.QRect(300, 110, 93, 28))
        self.rem.setObjectName(_fromUtf8("rem"))
        self.base10 = QtGui.QPushButton(Form)
        self.base10.setGeometry(QtCore.QRect(300, 190, 93, 28))
        self.base10.setObjectName(_fromUtf8("base10"))
        self.per = QtGui.QPushButton(Form)
        self.per.setGeometry(QtCore.QRect(500, 110, 93, 28))
        self.per.setObjectName(_fromUtf8("per"))
        self.com = QtGui.QPushButton(Form)
        self.com.setGeometry(QtCore.QRect(600, 110, 93, 28))
        self.com.setObjectName(_fromUtf8("com"))
        self.inv = QtGui.QPushButton(Form)
        self.inv.setGeometry(QtCore.QRect(600, 150, 93, 28))
        self.inv.setObjectName(_fromUtf8("inv"))
        self.clear = QtGui.QPushButton(Form)
        self.clear.setGeometry(QtCore.QRect(500, 190, 93, 28))
        self.clear.setObjectName(_fromUtf8("clear"))
        self.allclear = QtGui.QPushButton(Form)
        self.allclear.setGeometry(QtCore.QRect(600, 190, 93, 28))
        self.allclear.setObjectName(_fromUtf8("allclear"))
        self.point = QtGui.QPushButton(Form)
        self.point.setGeometry(QtCore.QRect(400, 230, 93, 28))
        self.point.setObjectName(_fromUtf8("point"))
        self.Oct = QtGui.QPushButton(Form)
        self.Oct.setGeometry(QtCore.QRect(600, 230, 93, 28))
        self.Oct.setObjectName(_fromUtf8("Oct"))
        self.hex = QtGui.QPushButton(Form)
        self.hex.setGeometry(QtCore.QRect(500, 230, 93, 28))
        self.hex.setObjectName(_fromUtf8("hex"))
        self.line = QtGui.QLineEdit(Form)
        self.line.setGeometry(QtCore.QRect(132, 20, 621, 22))
        self.line.setObjectName(_fromUtf8("line"))
        self.bckspc = QtGui.QPushButton(Form)
        self.bckspc.setGeometry(QtCore.QRect(700, 70, 51, 231))
        self.bckspc.setObjectName(_fromUtf8("bckspc"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "CALCULATOR", None))
        Form.setWindowIcon(QtGui.QIcon('kosslogo.png'))

        self.one.setText(_translate("Form", "1", None))
        self.two.setText(_translate("Form", "2", None))
        self.three.setText(_translate("Form", "3", None))
        self.four.setText(_translate("Form", "4", None))
        self.five.setText(_translate("Form", "5", None))
        self.six.setText(_translate("Form", "6", None))
        self.seven.setText(_translate("Form", "7", None))
        self.eight.setText(_translate("Form", "8", None))
        self.nine.setText(_translate("Form", "9", None))
        self.zero.setText(_translate("Form", "0", None))
        self.toolButton.setText(_translate("Form", "...", None))
        self.AT.setText(_translate("Form", "arctan", None))
        self.LN.setText(_translate("Form", "ln", None))
        self.add.setText(_translate("Form", "+", None))
        self.sub.setText(_translate("Form", "-", None))
        self.Sin.setText(_translate("Form", "sin", None))
        self.LOG.setText(_translate("Form", "log", None))
        self.Tan.setText(_translate("Form", "tan", None))
        self.basee.setText(_translate("Form", "e^x", None))
        self.equal.setText(_translate("Form", "=", None))
        self.fact.setText(_translate("Form", "x!", None))
        self.power.setText(_translate("Form", "x^y", None))
        self.AC.setText(_translate("Form", "arccos", None))
        self.mul.setText(_translate("Form", "*", None))
        self.sqr.setText(_translate("Form", "x^2", None))
        self.AS.setText(_translate("Form", "arcsin", None))
        self.Cos.setText(_translate("Form", "cos", None))
        self.div.setText(_translate("Form", "/", None))
        self.rem.setText(_translate("Form", "%", None))
        self.base10.setText(_translate("Form", "10^x", None))
        self.per.setText(_translate("Form", "npr", None))
        self.com.setText(_translate("Form", "ncr", None))
        self.inv.setText(_translate("Form", "1/x", None))
        self.clear.setText(_translate("Form", "CE", None))
        self.allclear.setText(_translate("Form", "C", None))
        self.point.setText(_translate("Form", ".", None))
        self.Oct.setText(_translate("Form", "OCT", None))
        self.hex.setText(_translate("Form", "HEX", None))
        self.bckspc.setText(_translate("Form", "<-", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

